In [1]:
import os
import pandas as pd

In [3]:
amrfinder_records = pd.read_csv('combined.tsv', sep='\t')
selected_amrfinder_genes = pd.read_csv('imipenem_shap_importance.csv')

In [4]:
selected_amrfinder_genes.head()

         gene  mean_abs_shap  mean_shap  std_shap  rank
0   blaOXA-23       0.623463  -0.194832  0.727015     1
1  blaOXA-100       0.266463   0.090157  0.400697     2
2   blaOXA-58       0.262747   0.051742  0.411650     3
3   blaOXA-71       0.228250  -0.043182  0.344853     4
4      tet(B)       0.198011  -0.001489  0.210549     5

In [5]:
selected_amrfinder_genes['rank'].nunique()

36

In [19]:
selected_amrfinder_genes['rank'].value_counts()

rank
69    62
24     2
29     2
35     2
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
26     1
27     1
28     1
31     1
32     1
33     1
34     1
37     1
38     1
Name: count, dtype: int64

In [28]:
top_rank_gene = selected_amrfinder_genes[selected_amrfinder_genes['rank']==1]['gene'].iloc[0]

In [29]:
top_rank_gene

'blaOXA-23'

In [31]:
amrfinder_records[amrfinder_records['Element symbol']==top_rank_gene]['biosample'].nunique()

12

In [32]:
amrfinder_records[amrfinder_records['Element symbol']==top_rank_gene]

,biosample,Protein id,Contig id,Start,Stop,Strand,Element symbol,Element name,Scope,Type,...,Method,Target length,Reference sequence length,% Coverage of reference,% Identity to reference,Alignment length,Closest reference accession,Closest reference name,HMM accession,HMM description
77,SAMN04014886,NaN,MPBW01000003.1,1076575,1077393,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
83,SAMN04014886,NaN,MPBW01000005.1,11692,12510,-,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
115,SAMN04014897,NaN,CP026706.1,50596,51414,-,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
453,SAMN04254731,NaN,LNCY01000084.1,1594,2412,-,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
473,SAMN04491039,NaN,AAYNND010000045.1,2774,3592,-,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
495,SAMN04491433,NaN,AAYNNB010000045.1,2774,3592,-,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4006,SAMN04901665,NaN,VYVC01000050.1,83,901,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4184,SAMN12087708,NaN,VHEK01000111.1,35,853,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4310,SAMN12087737,NaN,VHGD01000067.1,1599,2417,-,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4365,SAMN29439287,NaN,JAMZNM010000048.1,146,964,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4385,SAMN29439938,NaN,JAMZNL010000059.1,146,964,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4819,SAMN48878490,NaN,DBKROY010000115.1,34,852,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4832,SAMN48878490,NaN,DBKROY010000150.1,75,893,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4870,SAMN48878669,NaN,DBKRSB010000086.1,34,852,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN
4887,SAMN48878669,NaN,DBKRSB010000108.1,75,893,+,blaOXA-23,OXA-23 family carbapenem-hydrolyzing class D b...,core,AMR,...,ALLELEX,273,273,100.0,100.0,273,WP_001046004.1,OXA-23 family carbapenem-hydrolyzing class D b...,NaN,NaN